### ISSUE TITLE
Config - Change format from YAML to JSON

### ISSUE THREAD

**Issue by ryanemerson** [ryanemerson/aphrodite#8]

**Comment by elguardian** [comment]
probably 
https://json-processing-spec.java.net/nonav/releases/1.0/fcs/javadocs/index.html
or
https://jsonp.java.net/download.html

**Comment by ryanemerson** [comment]
Good idea, I'll use this when I make the change

**Comment by elguardian** [comment]
it is thin enough and does the job.
